/*
 * SwordfishSettingsDialog.java
 *
 * Created on Oct 6, 2008, 7:45:02 AM
 */
package swordfish.view;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import java.io.File;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;


/**
 * Currently not in use due to auto-connect.  Should be modified to change options
 * like buyIn, name, seat and the other configureable things for the player request
 * to the server
 * @author joshdavidson
 */
public class SwordfishSettingsDialog extends javax.swing.JDialog {

    private SwordfishView view;
    private static final String XML_HEADER = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
    
    /** Creates new form SwordfishSettingsDialog
     * @param parent Parent for the dialog
     * @param modal True for modal
     */
    public SwordfishSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadSettings();
        getRootPane().setDefaultButton(okButton);
    }

    /**
     * An overloaded constructor to allow talking to the view class
     * @param parent Parent frame
     * @param view View to communicate to
     * @param modal True for modal
     */
    public SwordfishSettingsDialog(java.awt.Frame parent, SwordfishView view, boolean modal) {
        super(parent, modal);
        this.view = view;
        initComponents();
        loadSettings();
        disableSettings();
        getRootPane().setDefaultButton(okButton);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stackButtonGroup = new javax.swing.ButtonGroup();
        nameTextField = new javax.swing.JTextField();
        logPathTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        buyInLabel = new javax.swing.JLabel();
        logPathLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        buyInTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(swordfish.view.SwordfishApp.class).getContext().getResourceMap(SwordfishSettingsDialog.class);
        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setName("nameTextField"); // NOI18N

        logPathTextField.setText(resourceMap.getString("logPathTextField.text")); // NOI18N
        logPathTextField.setName("logPathTextField"); // NOI18N

        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        buyInLabel.setText(resourceMap.getString("buyInLabel.text")); // NOI18N
        buyInLabel.setName("buyInLabel"); // NOI18N

        logPathLabel.setText(resourceMap.getString("logPathLabel.text")); // NOI18N
        logPathLabel.setName("logPathLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(swordfish.view.SwordfishApp.class).getContext().getActionMap(SwordfishSettingsDialog.class, this);
        okButton.setAction(actionMap.get("ok")); // NOI18N
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        cancelButton.setAction(actionMap.get("cancel")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        buyInTextField.setText(resourceMap.getString("buyInTextField.text")); // NOI18N
        buyInTextField.setName("buyInTextField"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(logPathLabel)
                            .add(nameLabel)
                            .add(buyInLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(logPathTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(buyInTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                    .add(layout.createSequentialGroup()
                        .add(89, 89, 89)
                        .add(okButton)
                        .add(18, 18, 18)
                        .add(cancelButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buyInLabel)
                    .add(buyInTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(logPathLabel)
                    .add(logPathTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Main for the class, useless for this application of the dialog
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SwordfishSettingsDialog dialog = new SwordfishSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Cancel button action hides the dialog
     */
    @Action
    public void cancel() {
        setVisible(false);
    }

    /**
     * OK button action saves the settings
     */
    @Action
    public void ok() {
        saveSettings();
        this.setVisible(false);
    }

    /**
     * Save the settings to the settings.xml file and show the information to the user
     */
    private void saveSettings() {
        try {
            savePlayerSettings();
            JOptionPane.showMessageDialog(this.getParent(), "Changes will take place next time you connect to a room", "",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this.getParent(), "Could not save settings file.", "Warning", JOptionPane.WARNING_MESSAGE);
            view.logWarning(ex.toString());
        }
    }

    /**
     * Actually write the settings to file.
     * @throws FileNotFoundException
     */
    private void savePlayerSettings() throws FileNotFoundException {
        File settings = new File("settings/settings.xml");
        PrintWriter xmlPrintWriter = new PrintWriter(settings);
        xmlPrintWriter.println(XML_HEADER);
        xmlPrintWriter.println("<Settings>");        
        xmlPrintWriter.println("<Name>" + nameTextField.getText() + "</Name>");
        xmlPrintWriter.println("<BuyIn>" + buyInTextField.getText() + "</BuyIn>");
        xmlPrintWriter.println("<LogPath>" + logPathTextField.getText() + "</LogPath>");        
        xmlPrintWriter.println("</Settings>");
        xmlPrintWriter.close();
    }

    /**
     * Load the settings to populate the dialog from disk.
     */
    private void loadSettings(){
       try {
            DocumentBuilderFactory docBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docBuilderFactory.newDocumentBuilder();
            Document doc = (Document) docBuilder.parse(new File("settings/settings.xml"));
            doc.getDocumentElement().normalize();

            NodeList settingsList = doc.getElementsByTagName("Settings");
            Node settingNode = settingsList.item(0);
            if (settingNode.getNodeType() == Node.ELEMENT_NODE) {
                Element element = (Element) settingNode;
                nameTextField.setText(element.getElementsByTagName("Name").item(0).getChildNodes().item(0).getNodeValue().trim());
                buyInTextField.setText(new Integer(element.getElementsByTagName("BuyIn").item(0).getChildNodes().item(0).getNodeValue().trim()).toString());
                logPathTextField.setText(element.getElementsByTagName("LogPath").item(0).getChildNodes().item(0).getNodeValue().trim());
            }
        } catch (ParserConfigurationException ex) {

        } catch (IOException ex) {

        } catch (SAXParseException ex) {

        } catch (SAXException ex) {

        }
    }

    /**
     * Disable all but the name settings
     */
    private void disableSettings() {        
        buyInTextField.setEnabled(false);
        logPathTextField.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buyInLabel;
    private javax.swing.JTextField buyInTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel logPathLabel;
    private javax.swing.JTextField logPathTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup stackButtonGroup;
    // End of variables declaration//GEN-END:variables
}
